services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER:-developer}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: clinica-saas-plataforma-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    env_file:
      - .env
    environment:
      - PGPASSWORD=${DB_PASSWORD}
    depends_on:
      - db
      - redis
    entrypoint: [".docker/entrypoint.sh"]
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: clinica-saas-plataforma-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: clinica-saas-plataforma-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
